# Generated by Django 4.2.3 on 2023-10-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('std', models.CharField(max_length=5)),
            ],
        ),
    ]
